package org.scify.jthinkfreedom.talkandplay.gui;

import javax.swing.ImageIcon;
import org.scify.jthinkfreedom.talkandplay.models.User;
import org.scify.jthinkfreedom.talkandplay.services.UserService;

/**
 *
 * @author peustr
 */
public class CreateUserScreen extends javax.swing.JFrame {

    private MainFrame caller;
    private UserService userService;

    /**
     * Creates new form CreateUserScreen
     */
    public CreateUserScreen() {
        initComponents();
    }

    public CreateUserScreen(MainFrame caller) {
        this.caller = caller;
        this.userService = new UserService();
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        pictureDescrLabel = new javax.swing.JLabel();
        pictureResizeLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nameDescrLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        defaultPhotoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Think Freedom");
        setResizable(false);

        contentPane.setBackground(new java.awt.Color(255, 255, 255));

        pictureDescrLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        pictureDescrLabel.setText("Upload a picture (optional)");

        pictureResizeLabel.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        pictureResizeLabel.setText("It will automatically be resized to 144x144");

        nameField.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N

        nameDescrLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        nameDescrLabel.setText("Name");

        continueButton.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        continueButton.setText("Save");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Error message");

        defaultPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/talkandplay/resources/no-photo.png"))); // NOI18N

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defaultPhotoLabel)
                    .addComponent(pictureDescrLabel)
                    .addComponent(pictureResizeLabel))
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(nameField)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                        .addComponent(nameDescrLabel)
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                        .addComponent(errorLabel)
                                        .addGap(49, 49, 49))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueButton)
                        .addContainerGap())))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameDescrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorLabel))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(defaultPhotoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(pictureDescrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pictureResizeLabel))
                    .addComponent(continueButton))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        String name = nameField.getText();
        for (ProfilePanel pp : caller.getProfilesPanel()) {
            if (pp.getProfile().getName().equals(name)) {
                errorLabel.setText("Name already exists!");
                return;
            }
        }
        if (!name.replaceAll("\\s+", "").isEmpty()) {
            // Add profile panel to profile screen
            // TODO: read image and resize it to 144x144
            User createdUser = new User(name,
                    new ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/talkandplay/resources/no-photo.png")));
            caller.getProfilesPanel().add(new ProfilePanel(caller, createdUser));
            caller.repaintProfiles();
            // Save to xml file
            userService.saveUser(createdUser);
            dispose();
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void initCustomComponents() {
        errorLabel.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel defaultPhotoLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel nameDescrLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel pictureDescrLabel;
    private javax.swing.JLabel pictureResizeLabel;
    // End of variables declaration//GEN-END:variables
}
