/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.jthinkfreedom.gui.forms;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.scify.jthinkfreedom.reactors.TileXmlParser;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author xrousakis
 */
public class AddTileScreen extends javax.swing.JFrame {

    private Map<String, String> peckingOrder;
    private Map<String, String> categoryFolders;
    DefaultListModel dlm;
    String selectedCategory;
    private String imageName;
    private String xml = System.getProperty("user.dir") + "/categories.xml";//"/home/xrousakis/JThinkFreedom/jthinkfreedom-reactors/categories.xml";
    public boolean reWrite;
    private Document configFile;
    private String existingCategory;
    private String existingImage;

    /**
     * Creates new form TileScreen
     */
    public AddTileScreen(String existingCategory, String existingText, String existingImage) {
        dlm = new DefaultListModel();
        reWrite = true;
        initComponents();
        categoryList.setSelectionMode(SINGLE_SELECTION);
        TileXmlParser parser = new TileXmlParser();
        peckingOrder = parser.getHierarchy();
        categoryFolders = parser.getCategoryFolders();
        /*category should remain the same*/
        selectedCategory = existingCategory;
        fillDlm();
        this.existingCategory = existingCategory;
        this.existingImage = existingImage;
        fillInfo(existingText, existingImage);
    }

    public AddTileScreen() {
        reWrite = false;
        dlm = new DefaultListModel();
        initComponents();
        categoryList.setSelectionMode(SINGLE_SELECTION);
        TileXmlParser parser = new TileXmlParser();
        peckingOrder = parser.getHierarchy();
        categoryFolders = parser.getCategoryFolders();
        fillDlm();
    }

    public void fillDlm() {
        for (Map.Entry<String, String> entry : peckingOrder.entrySet()) {
            dlm.addElement(entry.getKey());
        }
    }

    public void fillInfo(String existingText, String existingImage) {
        //categoryList.setValueIsAdjusting(existingCategory);
        categoryList.setSelectedValue(existingCategory, true);

        jTextField1.setText(existingText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();
        txtLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        textField = new javax.swing.JScrollPane();
        categoryList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 20)); // NOI18N
        jLabel1.setText("Add Image");

        imageLabel.setText("Select image:");

        imageButton.setText("Choose image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        txtLabel.setText("Give image text:");

        categoryLabel.setText("Select  Category");

        submitButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        submitButton.setText("Add");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        categoryList.setModel(dlm);
        categoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryListValueChanged(evt);
            }
        });
        textField.setViewportView(categoryList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLabel)
                    .addComponent(imageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageButton)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(categoryLabel)
                                .addContainerGap(59, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {imageButton, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imageLabel)
                            .addComponent(imageButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLabel)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Show the folder of the the category selected from the list*/
    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
               Border border = BorderFactory.createLineBorder(Color.RED, 2);
        if (selectedCategory == null) {
            categoryList.setBorder(border);
            return;
        }
        imageName = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(categoryFolders.get(selectedCategory)));
        chooser.setDialogTitle("Select Picture");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "png"));

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            imageName = chooser.getSelectedFile().getName();
        } else {

        }
    }//GEN-LAST:event_imageButtonActionPerformed


    private void categoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryListValueChanged
        if (reWrite == false) {
            selectedCategory = (String) categoryList.getSelectedValue();
            if (categoryList.getBorder() != null) {
                categoryList.setBorder(null);
            }
        } else {
            categoryList.setSelectedValue(existingCategory, true);
        }
    }//GEN-LAST:event_categoryListValueChanged

    private Border createBorder(Color color) {
        Border border = BorderFactory.createLineBorder(color, 2);
        return border;
    }

    /*Takes the  information from the components and inserts them into the xml*/
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String text = jTextField1.getText().toString();
        if (imageName == null) {
            JOptionPane.showMessageDialog(this, "you did not select an image");
        } else {
            if (text.equals("")) {
                jTextField1.setBorder(createBorder(Color.RED));
            } else {
                jTextField1.setBorder(null);
                if (reWrite == false) {
                    addToXml(text);
                } else {
                    reWriteXml(text);
                }
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /* Dispose current frame */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * get only the tile tags that belong to this category
     *
     * @param element
     * @return
     */
    private ArrayList<Node> getImmediateElementsByTagName(Element element, String tagName) {
        /*TODO: na epistrefei ta stoixeia mono tou sigegrimenou category element*/
        ArrayList<Node> list = new ArrayList<>();
        Element parent;
        NodeList tags = element.getElementsByTagName(tagName);
        for (int i = 0; i < tags.getLength(); i++) {
            parent = (Element) tags.item(i).getParentNode();
            String attribute = parent.getAttribute("name");
            String category_name = element.getAttribute("name");
            if (attribute.equalsIgnoreCase(category_name)) {
                list.add(tags.item(i));
            }
        }
        return list;
    }

    private void reWriteXml(String txt) {
        try {
            configFile = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(xml));
            configFile.normalize();
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
        }
        NodeList categories = configFile.getElementsByTagName("category");
        for (int i = 0; i < categories.getLength(); i++) {
            Element el = (Element) categories.item(i);
            if (el.getAttribute("name").equals(selectedCategory)) {
                ArrayList<Node> childTiles = getImmediateElementsByTagName(el, "tile");
                for (int j = 0; j < childTiles.size(); j++) {
                    Element tile = (Element) childTiles.get(j);
                    String folder = getImmediateElementsByTagName(el, "folder").get(0).getTextContent();
                    String fullpath = folder + "/" + tile.getElementsByTagName("filename").item(0).getTextContent();
                    /*if this is the Tile that i want to replace*/
                    if (fullpath.equals(existingImage)) {
                        tile.getElementsByTagName("filename").item(0).setTextContent(imageName);
                        tile.getElementsByTagName("text").item(0).setTextContent(txt);
                        try {
                            Transformer tr = TransformerFactory.newInstance().newTransformer();
                            tr.setOutputProperty(OutputKeys.INDENT, "yes");
                            tr.transform(new DOMSource(configFile),
                                    new StreamResult(new FileOutputStream(new File(xml))));
                        } catch (TransformerException | FileNotFoundException e) {
                            e.printStackTrace(System.err);
                        }
                    }
                }
            }
        }
    }

    /*Saves the information into the xml*/
    public void addToXml(String txt) {
        try {
            configFile = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(xml));
            configFile.normalize();
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
        }
        NodeList categories = configFile.getElementsByTagName("category");
        //System.out.println(categories.getLength());
        /* 
         creating tags to store 
         */
        Element tile = configFile.createElement("tile");
        Element filename = configFile.createElement("filename");
        Element text = configFile.createElement("text");
        filename.appendChild(configFile.createTextNode(imageName));
        /* 
         appending tags
         */
        text.appendChild(configFile.createTextNode(txt));
        tile.appendChild(filename);
        tile.appendChild(text);
        /*
         for all categories if this is the category that i chose append the tags
         */
        for (int i = 0; i < categories.getLength(); i++) {
            Element el = (Element) categories.item(i);
            if (el.getAttribute("name").equals(selectedCategory)) {
                categories.item(i).appendChild(tile);
                try {
                    Transformer tr = TransformerFactory.newInstance().newTransformer();
                    tr.setOutputProperty(OutputKeys.INDENT, "yes");
                    tr.transform(new DOMSource(configFile),
                            new StreamResult(new FileOutputStream(new File(xml))));

                } catch (TransformerException | FileNotFoundException e) {
                    e.printStackTrace(System.err);
                }
                JOptionPane.showMessageDialog(this, "New image added successfully");
            }
        }
        configFile.normalize();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTileScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JList categoryList;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submitButton;
    private javax.swing.JScrollPane textField;
    private javax.swing.JLabel txtLabel;
    // End of variables declaration//GEN-END:variables
}
