package org.scify.jthinkfreedom.gui.forms;

import org.scify.jthinkfreedom.gui.model.Configuration;

/**
 *
 * @author peustr
 */
public class ConfigurationPanel extends javax.swing.JPanel {

    private Configuration config;

    /**
     * Creates new form ConfigurationPanel
     */
    public ConfigurationPanel() {
        initComponents();
    }

    public ConfigurationPanel(Configuration config) {
        this.config = config;
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionLabel = new javax.swing.JLabel();
        sensorImage = new javax.swing.JLabel();
        sensorLabel = new javax.swing.JLabel();
        stimulusImage = new javax.swing.JLabel();
        stimulusLabel = new javax.swing.JLabel();
        reactorImage = new javax.swing.JLabel();
        reactorLabel = new javax.swing.JLabel();

        actionLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        actionLabel.setText("Action n");

        sensorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/gui/resources/webcam_49x64.png"))); // NOI18N
        sensorImage.setPreferredSize(new java.awt.Dimension(64, 64));

        sensorLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        sensorLabel.setText("Sensor Canonical String");

        stimulusImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/gui/resources/track_64x64.png"))); // NOI18N

        stimulusLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        stimulusLabel.setText("Stimulus Canonical String");

        reactorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/gui/resources/right_click_64x64.png"))); // NOI18N

        reactorLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        reactorLabel.setText("Reactor Canonical String");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sensorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sensorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stimulusImage)
                        .addGap(18, 18, 18)
                        .addComponent(stimulusLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reactorImage)
                        .addGap(18, 18, 18)
                        .addComponent(reactorLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sensorLabel)
                    .addComponent(sensorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(stimulusLabel)
                    .addComponent(stimulusImage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(reactorLabel)
                    .addComponent(reactorImage))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        sensorLabel.setText(config.getSensor().getCanonicalString());
        stimulusLabel.setText(config.getStimulus().getCanonicalString());
        reactorLabel.setText(config.getReactor().getCanonicalString());
        // TODO: Handling the motherfucking images somehow
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel reactorImage;
    private javax.swing.JLabel reactorLabel;
    private javax.swing.JLabel sensorImage;
    private javax.swing.JLabel sensorLabel;
    private javax.swing.JLabel stimulusImage;
    private javax.swing.JLabel stimulusLabel;
    // End of variables declaration//GEN-END:variables
}
