package org.scify.jthinkfreedom.gui.forms;

import java.awt.Color;
import javax.swing.Icon;

import javax.swing.JPanel;

import org.scify.jthinkfreedom.skeleton.reactors.ReactorAdapter;
import org.scify.jthinkfreedom.skeleton.sensors.SensorAdapter;
import org.scify.jthinkfreedom.skeleton.stimuli.StimulusAdapter;

/**
 *
 * @author peustr
 */
public class MinorComponent extends javax.swing.JPanel {

    // Either reactor panel, sensor panel, or stimulus panel
    private JPanel parent;

    // Either a reactor, a sensor, or a stimulus
    private ReactorAdapter reactor;
    private SensorAdapter sensor;
    private StimulusAdapter stimulus;

    /**
     * Creates new form MinorComponent
     */
    public MinorComponent() {
        initComponents();
    }

    public MinorComponent(JPanel parent, String text, Icon icon) {
        initComponents();
        this.parent = parent;
        this.titlePlaceholder.setText(text);
        this.imagePlaceholder.setIcon(icon);
    }

    public MinorComponent(ReactorAdapter reactor, JPanel parent, String text, Icon icon) {
        initComponents();
        this.reactor = reactor;
        this.parent = parent;
        this.titlePlaceholder.setText(text);
        this.imagePlaceholder.setIcon(icon);
    }

    public MinorComponent(SensorAdapter sensor, JPanel parent, String text, Icon icon) {
        initComponents();
        this.sensor = sensor;
        this.parent = parent;
        this.titlePlaceholder.setText(text);
        this.imagePlaceholder.setIcon(icon);
    }

    public MinorComponent(StimulusAdapter stimulus, JPanel parent, String text, Icon icon) {
        initComponents();
        this.stimulus = stimulus;
        this.parent = parent;
        this.titlePlaceholder.setText(text);
        this.imagePlaceholder.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePlaceholder = new javax.swing.JLabel();
        titlePlaceholder = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        imagePlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/gui/resources/circle_64x64.png"))); // NOI18N
        imagePlaceholder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagePlaceholderMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagePlaceholderMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagePlaceholderMouseEntered(evt);
            }
        });

        titlePlaceholder.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        titlePlaceholder.setText("Title");
        titlePlaceholder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePlaceholderMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                titlePlaceholderMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titlePlaceholderMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePlaceholder)
                .addGap(18, 18, 18)
                .addComponent(titlePlaceholder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(titlePlaceholder)
                    .addComponent(imagePlaceholder))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(246, 199, 159));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formMouseExited

    private void imagePlaceholderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagePlaceholderMouseEntered
        setBackground(new Color(246, 199, 159));
    }//GEN-LAST:event_imagePlaceholderMouseEntered

    private void imagePlaceholderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagePlaceholderMouseExited
        setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_imagePlaceholderMouseExited

    private void titlePlaceholderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePlaceholderMouseEntered
        setBackground(new Color(246, 199, 159));
    }//GEN-LAST:event_titlePlaceholderMouseEntered

    private void titlePlaceholderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePlaceholderMouseExited
        setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_titlePlaceholderMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        handleClicks();
    }//GEN-LAST:event_formMouseClicked

    private void imagePlaceholderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagePlaceholderMouseClicked
        handleClicks();
    }//GEN-LAST:event_imagePlaceholderMouseClicked

    private void titlePlaceholderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePlaceholderMouseClicked
        handleClicks();
    }//GEN-LAST:event_titlePlaceholderMouseClicked

    private void handleClicks() {
        if (parent instanceof ReactorPanel) {
            ((ReactorPanel) parent).updateBreadcrumbs(reactor.getCanonicalString() + "/");
            ((ReactorPanel) parent).transitionToSensors();
            ((ReactorPanel) parent).setReactorClass(reactor);

        } else if (parent instanceof SensorPanel) {
            ((SensorPanel) parent).updateBreadcrumbs(sensor.getCanonicalString() + "/");
            ((SensorPanel) parent).transitionToStimuli();
            ((SensorPanel) parent).setSensorClass(sensor);
        } else if (parent instanceof StimulusPanel) {
            ((StimulusPanel) parent).updateBreadcrumbs(stimulus.getCanonicalString());
            ((StimulusPanel) parent).activateSaveButton();
            ((StimulusPanel) parent).setStimulusClass(stimulus);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagePlaceholder;
    private javax.swing.JLabel titlePlaceholder;
    // End of variables declaration//GEN-END:variables
}
