package org.scify.jthinkfreedom.gui.forms;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import org.scify.jthinkfreedom.gui.model.Configuration;
import org.scify.jthinkfreedom.gui.model.User;

/**
 *
 * @author peustr
 */
public class ProfilePanel extends javax.swing.JPanel {

    private ProfileScreen parent;
    private User profile;

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    public ProfilePanel(ProfileScreen parent, User profile) {
        this.parent = parent;
        this.profile = profile;
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        selectLabel = new javax.swing.JLabel();
        configureLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/gui/resources/placeholder_144x144.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        nameLabel.setText("Name");

        selectLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        selectLabel.setForeground(new java.awt.Color(51, 51, 255));
        selectLabel.setText("Select");
        selectLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectLabelMouseEntered(evt);
            }
        });

        configureLabel.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        configureLabel.setForeground(new java.awt.Color(51, 51, 255));
        configureLabel.setText("Configure");
        configureLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configureLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configureLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configureLabel))
                    .addComponent(nameLabel)
                    .addComponent(imageLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configureLabel)
                    .addComponent(selectLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLabelMouseClicked
        parent.getConfigurations().clear();
        for (Configuration config : profile.getConfigurations()) {
            parent.getConfigurations().add(new ConfigurationPanel(config));
        }
        parent.repaintConfigurations(profile);
    }//GEN-LAST:event_selectLabelMouseClicked

    private void selectLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLabelMouseEntered
        originalFont = selectLabel.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        selectLabel.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_selectLabelMouseEntered

    private void selectLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLabelMouseExited
        selectLabel.setFont(originalFont);
    }//GEN-LAST:event_selectLabelMouseExited

    private void configureLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureLabelMouseEntered
        originalFont = configureLabel.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        configureLabel.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_configureLabelMouseEntered

    private void configureLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureLabelMouseExited
        configureLabel.setFont(originalFont);
    }//GEN-LAST:event_configureLabelMouseExited

    private void initCustomComponents() {
        nameLabel.setText(profile.getName());
        imageLabel.setIcon(profile.getPhoto());
    }

    private Font originalFont;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel configureLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel selectLabel;
    // End of variables declaration//GEN-END:variables
}
