/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.jthinkfreedom.gui.forms;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.border.Border;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.scify.jthinkfreedom.reactors.Tile;
import org.scify.jthinkfreedom.reactors.TileXmlParser;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author xrousakis
 */
public class RemoveTileScreen extends javax.swing.JFrame {

    private Map<String, String> peckingOrder;
    private Map<String, ArrayList<Tile>> tiles;
    private Map<String, List<String>> categoryItems;
    private String selectedImage;
    private String xml = System.getProperty("user.dir") + "/categories.xml";
    private DefaultListModel categoriesDlm;
    private DefaultListModel imagesDlm;
    private Document configFile;
    private String selectedCategory;

    public RemoveTileScreen() {
        imagesDlm = new DefaultListModel();
        categoriesDlm = new DefaultListModel();
        initComponents();
        categoryList.setSelectionMode(SINGLE_SELECTION);
        TileXmlParser parser = new TileXmlParser();
        categoryItems = parser.getCategoryItems();
        peckingOrder = parser.getHierarchy();
        tiles = parser.getTiles();
        fillCategoriesDlm();
    }

    public void fillCategoriesDlm() {
        for (Map.Entry<String, String> entry : peckingOrder.entrySet()) {
            categoriesDlm.addElement(entry.getKey());
        }
    }

    public void fillImagesDlm() {
        ArrayList<String> items = (ArrayList<String>) categoryItems.get(selectedCategory);
        imagesDlm.clear();
        for (String s : items) {
            imagesDlm.addElement(s);
            //System.out.println(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        imageList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("Remove Image");

        categoryList.setModel(categoriesDlm);
        categoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(categoryList);

        jLabel2.setText("Select Category");

        confirmButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(249, 6, 6));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        imageList.setModel(imagesDlm);
        imageList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                imageListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(imageList);

        jLabel3.setText("Select Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(59, 59, 59))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    private void categoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryListValueChanged
        if (evt.getValueIsAdjusting()) {
            selectedCategory = (String) categoryList.getSelectedValue();
            selectedImage = null;
            fillImagesDlm();
        }
    }//GEN-LAST:event_categoryListValueChanged


    private void imageListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_imageListValueChanged
        if (evt.getValueIsAdjusting()) {
            selectedImage = (String) imageList.getSelectedValue();
        }
    }//GEN-LAST:event_imageListValueChanged

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        Border border = BorderFactory.createLineBorder(Color.RED, 2);
        if (selectedImage == null) {
            JOptionPane.showMessageDialog(this, "You didnt select and image.");
        } else {
            deleteFromXml();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    /*
     retireves the tile elements that belong to this category
     */
    private ArrayList<Node> getImmediateElementsByTagName(Element element) {
        /*TODO: na epistrefei ta stoixeia mono tou sigegrimenou category element*/
        ArrayList<Node> list = new ArrayList<>();
        Element parent;
        NodeList tags = element.getElementsByTagName("tile");
        for (int i = 0; i < tags.getLength(); i++) {
            parent = (Element) tags.item(i).getParentNode();
            String attribute = parent.getAttribute("name");
            String category_name = element.getAttribute("name");
            if (attribute.equalsIgnoreCase(category_name)) {
                list.add(tags.item(i));
            }
        }
        return list;
    }

    /* 
     Delete from xml file the chosen tile (image and text)
     */
    public void deleteFromXml() {
        try {
            configFile = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(xml));
            configFile.normalize();
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
        }
        NodeList categories = configFile.getElementsByTagName("category");

        for (int i = 0; i < categories.getLength(); i++) {
            Element el = (Element) categories.item(i);
            if (el.getAttribute("name").equals(selectedCategory)) {
                ArrayList<Node> childTiles = getImmediateElementsByTagName(el);
                System.out.println(childTiles.size());
                for (int j = 0; j < childTiles.size(); j++) {
                    Element tile = (Element) childTiles.get(j);
                    String fullname = tile.getElementsByTagName("filename").item(0).getTextContent();
                    if (fullname.equals(selectedImage)) {
                        el.removeChild(tile);
                        try {
                            Transformer tr = TransformerFactory.newInstance().newTransformer();
                            tr.setOutputProperty(OutputKeys.INDENT, "yes");
                            tr.transform(new DOMSource(configFile),
                                    //new StreamResult(new FileOutputStream (new File(getClass().getResource("/conf.xml").toURI())) ));
                                    new StreamResult(new FileOutputStream(new File(xml))));
                        } catch (TransformerException | FileNotFoundException e) {
                            e.printStackTrace(System.err);
                        }
                         JOptionPane.showMessageDialog(this, "Image Removed.");
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveTileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveTileScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList categoryList;
    private javax.swing.JButton confirmButton;
    private javax.swing.JList imageList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
