/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.jthinkfreedom.talkandplay.gui.configuration;

import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.scify.jthinkfreedom.talkandplay.models.Category;
import org.scify.jthinkfreedom.talkandplay.models.Configuration;
import org.scify.jthinkfreedom.talkandplay.models.User;

/**
 *
 * @author christina
 */
public class CommunicationModuleSettingsPanel extends javax.swing.JPanel {
    
    private List<User> profiles;
    private JPanel categoryPanel;
    
    public CommunicationModuleSettingsPanel(List<User> profiles) {
        this.profiles = profiles;
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        categoriesPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Categories");

        categoriesPanel.setBackground(new java.awt.Color(255, 255, 255));
        categoriesPanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
        categoriesPanel.setLayout(categoriesPanelLayout);
        categoriesPanelLayout.setHorizontalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        categoriesPanelLayout.setVerticalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        categoriesPanel.setLayout(new BoxLayout(categoriesPanel, BoxLayout.Y_AXIS));
        categoriesPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
    }
    
    public void repaintSettings(User profile) {        
        for (Configuration configuration : profile.getConfigurations()) {
            categoriesPanel.removeAll();
            drawCategories(configuration.getCategories());
            
            categoriesPanel.revalidate();
            categoriesPanel.repaint();
        }        
    }

    /**
     * Recursively draw the categories and subcategories, no matter how deep the
     * levels are
     *
     * @param categories
     */
    private void drawCategories(List<Category> categories) {
        if (categories.size() == 0) {
            return;
        } else {
            for (Category category : categories) {
                categoryPanel = new JPanel();
                categoryPanel.setBackground(Color.white);
                JTextField textField = new JTextField(category.getName(), 10);
                categoryPanel.add(textField);
                textField = new JTextField((new Integer(category.getRows())).toString(), 5);
                categoryPanel.add(textField);
                textField = new JTextField((new Integer(category.getColumns())).toString(), 5);
                
                categoryPanel.add(textField);
                categoryPanel.setLayout(new FlowLayout());
                categoryPanel.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
                categoriesPanel.add(categoryPanel);
                
                drawCategories(category.getSubCategories());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
