package org.scify.jthinkfreedom.talkandplay.gui.configuration;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.scify.jthinkfreedom.talkandplay.gui.ConfigurationFrame;
import org.scify.jthinkfreedom.talkandplay.gui.MainFrame;
import org.scify.jthinkfreedom.talkandplay.gui.helpers.GuiHelper;
import org.scify.jthinkfreedom.talkandplay.models.User;
import org.scify.jthinkfreedom.talkandplay.services.UserService;

public class GeneralSettingsPanel extends javax.swing.JPanel {
    
    private User user;
    private UserService userService;
    private ConfigurationFrame configurationFrame;
    private MainFrame mainFrame;
    private GuiHelper guiHelper;
    private String userImage;

    /**
     * Creates new form ConfigurationPanel
     */
    public GeneralSettingsPanel(ConfigurationFrame configurationFrame, MainFrame mainFrame) {
        this.configurationFrame = configurationFrame;
        this.mainFrame = mainFrame;
        this.userService = new UserService();
        this.guiHelper = new GuiHelper();
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalSettingsPanel = new javax.swing.JPanel();
        profileNameLabel = new javax.swing.JLabel();
        profileNameField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        uploadImageButton = new javax.swing.JButton();
        rotationSpeedLabel = new javax.swing.JLabel();
        rotationSpeedTextField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        preselectedCheckbox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        generalSettingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        generalSettingsPanel.setForeground(new java.awt.Color(255, 255, 255));
        generalSettingsPanel.setMinimumSize(new java.awt.Dimension(100, 20));

        profileNameLabel.setText("Όνομα προφίλ:");

        profileNameField.setMinimumSize(new java.awt.Dimension(100, 23));

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setForeground(new java.awt.Color(51, 51, 51));
        deleteButton.setText("Διαγραφή");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setForeground(new java.awt.Color(51, 51, 51));
        saveButton.setText("Αποθήκευση");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/talkandplay/resources/no-photo.png"))); // NOI18N

        uploadImageButton.setBackground(new java.awt.Color(255, 255, 255));
        uploadImageButton.setForeground(new java.awt.Color(51, 51, 51));
        uploadImageButton.setText("Αλλαγή εικόνας");
        uploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageButtonActionPerformed(evt);
            }
        });

        rotationSpeedLabel.setText("Ταχύτητα scanning:");

        rotationSpeedTextField.setMinimumSize(new java.awt.Dimension(100, 23));
        rotationSpeedTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        errorLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorLabel.setText("Παρακαλώ συμπληρώστε σωστά όλα τα πεδία");

        preselectedCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        preselectedCheckbox.setForeground(new java.awt.Color(51, 51, 51));
        preselectedCheckbox.setText("Προεπιλεγμένο προφίλ");

        javax.swing.GroupLayout generalSettingsPanelLayout = new javax.swing.GroupLayout(generalSettingsPanel);
        generalSettingsPanel.setLayout(generalSettingsPanelLayout);
        generalSettingsPanelLayout.setHorizontalGroup(
            generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(uploadImageButton))
                    .addComponent(imageLabel))
                .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(deleteButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saveButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalSettingsPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(errorLabel)))
                    .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                                .addComponent(profileNameLabel)
                                .addGap(49, 49, 49)
                                .addComponent(profileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(preselectedCheckbox)
                            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                                .addComponent(rotationSpeedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rotationSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        generalSettingsPanelLayout.setVerticalGroup(
            generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profileNameLabel)
                            .addComponent(profileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotationSpeedLabel)
                            .addComponent(rotationSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preselectedCheckbox)
                        .addGap(41, 41, 41)
                        .addComponent(errorLabel))
                    .addComponent(imageLabel))
                .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(saveButton)))
                    .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(uploadImageButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(generalSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        if (profileNameField.getText().isEmpty()) {
            errorLabel.setVisible(true);
        } else {
            errorLabel.setVisible(false);
            
            User updatedUser = new User(profileNameField.getText(), this.userImage, Integer.parseInt(rotationSpeedTextField.getText()));
            updatedUser.setPreselected(preselectedCheckbox.isSelected());
            
            try {
                userService.update(updatedUser, user.getName());
            } catch (Exception ex) {
                Logger.getLogger(GeneralSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            configurationFrame.updateUsersList(profileNameField.getText());
            
            mainFrame.updateProfilesPanel(updatedUser, user.getName());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        int dialogResult = JOptionPane.showConfirmDialog(null, "Είστε σίγουροι ότι θέλετε να διαγράψετε το προφίλ?", "Warning", 0);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                userService.delete(new User(profileNameField.getText()));
            } catch (Exception ex) {
                Logger.getLogger(GeneralSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            configurationFrame.removeFromUsersList();
            mainFrame.removeFromProfilesPanel(user.getName());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void uploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageButtonActionPerformed
        userImage = "";
        JFileChooser chooser = new JFileChooser();
        
        chooser.setDialogTitle("Διαλέξτε εικόνα");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setFileFilter(new FileNameExtensionFilter("Image Files", "png", "jpg", "jpeg", "JPG", "JPEG", "gif"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            userImage = chooser.getSelectedFile().getAbsolutePath();
            imageLabel.setIcon(guiHelper.getIcon(userImage));
        }
    }//GEN-LAST:event_uploadImageButtonActionPerformed
    
    private void initCustomComponents() {
        hideElements();
    }
    
    public void repaintSettings(User user) throws IOException {
        deleteButton.setVisible(true);
        saveButton.setVisible(true);
        profileNameField.setVisible(true);
        profileNameLabel.setVisible(true);
        imageLabel.setVisible(true);
        rotationSpeedLabel.setVisible(true);
        rotationSpeedTextField.setVisible(true);
        uploadImageButton.setVisible(true);
        preselectedCheckbox.setVisible(true);
        
        imageLabel.setIcon(guiHelper.getIcon(user.getImage()));
        
        profileNameField.setText(user.getName());
        rotationSpeedTextField.setText(String.valueOf(user.getRotationSpeed()));
        preselectedCheckbox.setSelected(user.isPreselected());
        this.user = user;
    }
    
    public void hideElements() {
        deleteButton.setVisible(false);
        saveButton.setVisible(false);
        profileNameField.setVisible(false);
        profileNameLabel.setVisible(false);
        imageLabel.setVisible(false);
        rotationSpeedLabel.setVisible(false);
        rotationSpeedTextField.setVisible(false);
        uploadImageButton.setVisible(false);
        errorLabel.setVisible(false);
        preselectedCheckbox.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel generalSettingsPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JCheckBox preselectedCheckbox;
    private javax.swing.JTextField profileNameField;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JLabel rotationSpeedLabel;
    private javax.swing.JTextField rotationSpeedTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton uploadImageButton;
    // End of variables declaration//GEN-END:variables
}
